name: Run on Changes

on:
  push:
    paths:
      - 'src/*'
      - 'flake.*'
      - 'Cargo.*'
  pull_request:
    paths:
      - 'src/*'
      - 'flake.*'
      - 'Cargo.*'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Nix build
        run: |
          nix build
